# Basic Information 
title: Junyi Wu
position: Ph.D. student
affiliation: Illinois Institute of Technology
# affiliation_link: https://cs.jhu.edu/
# affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: jwu125 (at) hawk.iit.edu
# email2: yliu538 (at) jhu.edu

# Search Engine Optimization (SEO)
keywords: junyi wu, wu junyi, junyiwu, wujunyi
# description: Yaoyao Liu is a postdoctoral fellow at Johns Hopkins University. His research lies in meta-learning, incremental learning, and image generation.

# The option is used to enable the Johns Hopkins template.
# enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=JlbNwMAAAAAJ&hl=zh-CN&authuser=1
# cv_link: https://pages.jh.edu/yliu538/files/Yaoyao_Liu_Curriculum_Vitae.pdf
# github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/junyi-wu-82a92b24a/
twitter: https://twitter.com/JunyiWu81518643

# Images 
avatar: ./assets/img/photo.jpg
favicon: ./assets/img/IMG_4359.png
favicon_dark: ./assets/img/IMG_4359.png

# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
